### ISSUE TITLE
修改訂單 訂單統計不會計算

### ISSUE THREAD

**Issue by xz-exp** [john8895/wanna-eat#2]
修改訂單 訂單統計不會計算

**Comment by john8895** [comment]
修改完訂單要按 enter 或點旁邊一下，你試試看！

**Comment by xz-exp** [comment]
> 修改完訂單要按 enter 或點旁邊一下，你試試看！

我一開始也已為沒有enter 
敲enter只會記錄.
因此我去去新增第三筆訂單 -80之後的 下一筆
總計數量算除是 300
過程是這樣的

測試一
1.	新增第一筆 +100
2.	新增第二筆 -100
統計出來 +200  

測試二
修改第二筆 -100 為 -80 或任意數直 統計數直 依然是 200

測試三
新增第三筆 +100 統計訂單為 +300

**Comment by xz-exp** [comment]
http://eat.jgui.tw/order.php?id=210422053242 測試訂單

https://imgur.com/a/HznMGum

**Comment by john8895** [comment]
這邊出現的問題是：相同餐點設定不同價格無法判別，但這種情況不應出現，所以不是應判斷此情況，而是應提示此錯誤。

**Comment by xz-exp** [comment]
https://imgur.com/a/RdKJ2bo
這個情況出現很容易喔!  是有點機車沒錯 但是辦公室啥情況都有 尤其是飲料 加料 .甜度. 冰塊

https://imgur.com/a/qqbSKDB
手工麵 還會加收10塊錢 同一個餐點

**Comment by john8895** [comment]
因為餐點名只有一個欄位，所以加點項目不同，餐點名應該寫不同，例如三個餛飩麵加點不同，不能都寫「餛飩麵」，而是應該寫「餛飩麵＋滷蛋」、「餛飩麵＋手工麵」、「餛飩麵＋小菜」，如果都寫餛飩麵，點餐的人也沒法點。

會設定相同品名應該一樣價格，是因為訂單統計必須將「相同品名」的餐點統一計算，例如有三個排骨飯，要統計在一起，不能寫三筆，這樣訂餐的人才好叫餐：直接說排骨飯三個。

**Comment by xz-exp** [comment]
原來如此 謝謝!

**Comment by john8895** [comment]
不會，有問題請再提出，謝謝！
